app:
  jwt:
    secret: r4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUj
    expiration:
      minutes: 8600
spring:
  application:
    name: authorization-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authorization-service
      authentication-database: admin
      username: root
      password: root
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    password: elelel
server:
  port: '0'
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekauser:eureka@${eureka.instance.hostname}:8761/eureka/