debug: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: '8765'
spring:
  cloud:
    config:
      profile: dev
    gateway:
      discovery.locator.enabled: true
  config:
    import: optional:configserver:false
  gateway:
    excludedURLsNew: /auth/authenticate,/auth/signup
  application:
    name: api-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 15
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekauser:eureka@${eureka.instance.hostname}:8761/eureka/